### ISSUE TITLE
$allowInstabreak error.

### ISSUE THREAD

**Issue by akaSnapy** [FrontierDevs/Genisys3#5]
When i'm breaking blocks this will pop-up.in console: Notice: Undefined property: pocketmine\Server::$allowInstabreak in /root/Genisys3/src/pocketmine/level/Level.php on line 1613

* Genisys:1.1.0
* PHP:7.0.15
* Server OS:Ubuntu
* Game version: 1.0.5

**Comment by xXSirGamesXx** [comment]
ill look into it

**Comment by Johnmacrocraft** [comment]
It seems like I found the reason why this happens.
Level.php (PocketMine-MP and Genisys): $ev = new BlockBreakEvent($player, $target, $item, ($player->isCreative() or $player->allowInstaBreak()));
Level.php (Tesseract): $ev = new BlockBreakEvent($player, $target, $item, ($player->isCreative() or $this->server->allowInstabreak));

This seems to be happened because we forked Tesseract Code and trying to make it as Genisys. I think we should fork it again from Genisys, it's completely messed up.

**Comment by xXSirGamesXx** [comment]
tested and is correct. I pinpointed the issue, its an error from src/pocketmine/blocks;

**Comment by xXSirGamesXx** [comment]
its gonna take a while to find out which block it is that needs fixing

**Comment by xXSirGamesXx** [comment]
we don't have to redo everything. I think I've come up with a fix

**Comment by xXSirGamesXx** [comment]
itsonly one file error. I forked Level.php from dead genisys. fixed this issue. Thanks for reporting Snapy
